version: '2'

services:
  
  wordpress:
    image: wordpress:4.6.1-apache
    ports:
      - 8082:80
    volumes:
      - ./wp-content:/var/www/htnl/wp-content
    links:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: wp

  mysql:
    image: mariadb:10.1.17
    ports:
      - 8083:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wp